// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzMm-jnmyFiqN_VulrQwvoqxV72RVQNoM',
    appId: '1:281099055112:web:d53862b94963acc432a1bd',
    messagingSenderId: '281099055112',
    projectId: 'mis-lab-211022',
    authDomain: 'mis-lab-211022.firebaseapp.com',
    storageBucket: 'mis-lab-211022.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBglyxDDRXEIBpfPX_93TFW2swLcrdpDwQ',
    appId: '1:281099055112:android:31004716e2f93e7532a1bd',
    messagingSenderId: '281099055112',
    projectId: 'mis-lab-211022',
    storageBucket: 'mis-lab-211022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdFGFwoproURE_D7vhpLIONrdHkIpq9kU',
    appId: '1:281099055112:ios:229f5472f3ae3fe332a1bd',
    messagingSenderId: '281099055112',
    projectId: 'mis-lab-211022',
    storageBucket: 'mis-lab-211022.firebasestorage.app',
    iosBundleId: 'com.example.jokeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdFGFwoproURE_D7vhpLIONrdHkIpq9kU',
    appId: '1:281099055112:ios:229f5472f3ae3fe332a1bd',
    messagingSenderId: '281099055112',
    projectId: 'mis-lab-211022',
    storageBucket: 'mis-lab-211022.firebasestorage.app',
    iosBundleId: 'com.example.jokeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzMm-jnmyFiqN_VulrQwvoqxV72RVQNoM',
    appId: '1:281099055112:web:ebd745c8c641c78d32a1bd',
    messagingSenderId: '281099055112',
    projectId: 'mis-lab-211022',
    authDomain: 'mis-lab-211022.firebaseapp.com',
    storageBucket: 'mis-lab-211022.firebasestorage.app',
  );

}